// Generated by packages/contracts/scripts/generate-mandate-abi.mjs from C:\Users\HP Victus\Documents\personal-projects\hackathon\ethonline\mandate\/contracts/out/MandateAquaApp.sol/MandateAquaApp.json.
import type { Abi } from "viem";

export const mandateAquaAppAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "aqua",
        "type": "address",
        "internalType": "contract IAqua"
      },
      {
        "name": "maxMandateDuration",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "AQUA",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IAqua"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_MANDATE_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "activate",
    "inputs": [
      {
        "name": "strategy",
        "type": "tuple",
        "internalType": "struct MandateAquaApp.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agent",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensRegistry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensResolver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensLabel",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "ensNode",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenOut",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapTarget",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapSelector",
            "type": "bytes4",
            "internalType": "bytes4"
          },
          {
            "name": "minRateNumerator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minRateDenominator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputPerCall",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputTotal",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "validAfter",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "execute",
    "inputs": [
      {
        "name": "strategy",
        "type": "tuple",
        "internalType": "struct MandateAquaApp.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agent",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensRegistry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensResolver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensLabel",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "ensNode",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenOut",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapTarget",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapSelector",
            "type": "bytes4",
            "internalType": "bytes4"
          },
          {
            "name": "minRateNumerator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minRateDenominator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputPerCall",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputTotal",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "validAfter",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "agentMinOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "executionDeadline",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "routeData",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "amountOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "inspect",
    "inputs": [
      {
        "name": "strategy",
        "type": "tuple",
        "internalType": "struct MandateAquaApp.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agent",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensRegistry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensResolver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensLabel",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "ensNode",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenOut",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapTarget",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapSelector",
            "type": "bytes4",
            "internalType": "bytes4"
          },
          {
            "name": "minRateNumerator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minRateDenominator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputPerCall",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputTotal",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "validAfter",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct MandateAquaApp.Inspection",
        "components": [
          {
            "name": "strategyHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "usedInput",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "activated",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "revoked",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "mandates",
    "inputs": [
      {
        "name": "strategyHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "maker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "usedInput",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "activated",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "revoked",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minimumOutput",
    "inputs": [
      {
        "name": "strategy",
        "type": "tuple",
        "internalType": "struct MandateAquaApp.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agent",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensRegistry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensResolver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensLabel",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "ensNode",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenOut",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapTarget",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapSelector",
            "type": "bytes4",
            "internalType": "bytes4"
          },
          {
            "name": "minRateNumerator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minRateDenominator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputPerCall",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputTotal",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "validAfter",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "revoke",
    "inputs": [
      {
        "name": "hash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "strategyHash",
    "inputs": [
      {
        "name": "strategy",
        "type": "tuple",
        "internalType": "struct MandateAquaApp.Strategy",
        "components": [
          {
            "name": "maker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agent",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensRegistry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensResolver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ensLabel",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "ensNode",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "tokenIn",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "tokenOut",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapTarget",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "swapSelector",
            "type": "bytes4",
            "internalType": "bytes4"
          },
          {
            "name": "minRateNumerator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minRateDenominator",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputPerCall",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxInputTotal",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "validAfter",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "validUntil",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "event",
    "name": "MandateActivated",
    "inputs": [
      {
        "name": "strategyHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "agent",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "strategy",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MandateExecuted",
    "inputs": [
      {
        "name": "strategyHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "agent",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amountIn",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "amountOut",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "usedInputAfter",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MandateRevoked",
    "inputs": [
      {
        "name": "strategyHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "maker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyActivated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AquaBalanceInsufficient",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AquaStrategyInactive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ENSAddressMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ENSExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ENSNotRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ENSOwnerMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExecutionDeadlineExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InputNotFullySpent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InputTransferMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidStrategy",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MandateInactive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MandateRevokedError",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotAgent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotMaker",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotStarted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OutputTooLow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PerCallCapExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ResidualAllowance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ResidualBalance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RouteCallFailed",
    "inputs": [
      {
        "name": "selector",
        "type": "bytes4",
        "internalType": "bytes4"
      },
      {
        "name": "reasonHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TotalCapExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongSelector",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  }
] as const satisfies Abi;
